# Generated by Django 2.2.7 on 2020-02-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_auto_20200211_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='img',
            field=models.ImageField(upload_to='Q_Pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, upload_to='User_Pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
